[[target]]
name = "foo"
description = "Print the blueprint contents"
command = "cat"
args = ["{{orbit.blueprint}}"]

[test]
default-target = "foo"

[build]
default-target = "foo"

[vhdl-format]
highlight-syntax = true

[verilog-format]
highlight-syntax = true